version: "3.2"

services:
  web:
    image: nginx:1.15-alpine
    restart: always
    volumes:
      - ${APP_ROOT}:/app
  php:
    build: ./docker/php
    restart: always
    volumes:
      - ./bin/composer:/usr/local/bin/composer
      - ${APP_ROOT}:/app
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  mongodb:
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  redis:
    image: redis:4.0-stretch
    restart: always
  xunsearch:
    image: hightman/xunsearch:latest
